"""Canonical skills taxonomy — the seed list for `skills_catalog`.

Format: (name, category, aliases)
Categories: language | framework | platform | tool | domain

Curated for breadth across the seed-data personas the demo uses. Aliases are
matched case-insensitively during extraction to canonicalize variants
(e.g. "JS", "Javascript" → "JavaScript").
"""

from typing import Final

CANONICAL_SKILLS: Final[list[tuple[str, str, list[str]]]] = [
    # ─── Languages ────────────────────────────────────────────────
    ("JavaScript", "language", ["JS", "Javascript", "ECMAScript"]),
    ("TypeScript", "language", ["TS"]),
    ("Python", "language", ["Python3", "py"]),
    ("Java", "language", []),
    ("Go", "language", ["Golang"]),
    ("Rust", "language", []),
    ("C++", "language", ["CPP", "Cpp"]),
    ("C#", "language", ["C-Sharp", "CSharp"]),
    ("Ruby", "language", []),
    ("PHP", "language", []),
    ("Kotlin", "language", []),
    ("Swift", "language", []),
    ("SQL", "language", []),
    ("Bash", "language", ["Shell", "shell scripting"]),
    # ─── Frameworks / Libraries ───────────────────────────────────
    ("React", "framework", ["React.js", "ReactJS"]),
    ("Next.js", "framework", ["NextJS", "Next"]),
    ("Vue.js", "framework", ["Vue", "VueJS"]),
    ("Angular", "framework", ["AngularJS"]),
    ("Svelte", "framework", ["SvelteKit"]),
    ("React Native", "framework", []),
    ("Node.js", "framework", ["NodeJS", "Node"]),
    ("Express.js", "framework", ["Express"]),
    ("NestJS", "framework", ["Nest.js"]),
    ("FastAPI", "framework", []),
    ("Django", "framework", []),
    ("Flask", "framework", []),
    ("Spring Boot", "framework", ["Spring"]),
    ("Ruby on Rails", "framework", ["Rails", "RoR"]),
    ("Laravel", "framework", []),
    ("TensorFlow", "framework", ["TF"]),
    ("PyTorch", "framework", ["Torch"]),
    ("LangChain", "framework", []),
    ("Tailwind CSS", "framework", ["Tailwind", "TailwindCSS"]),
    ("Socket.IO", "framework", ["socket.io", "SocketIO"]),
    # ─── Platforms / Cloud / Data ─────────────────────────────────
    ("AWS", "platform", ["Amazon Web Services"]),
    ("AWS Lambda", "platform", ["Lambda"]),
    ("AWS S3", "platform", ["S3"]),
    ("AWS EC2", "platform", ["EC2"]),
    ("GCP", "platform", ["Google Cloud", "Google Cloud Platform"]),
    ("Azure", "platform", ["Microsoft Azure"]),
    ("Vercel", "platform", []),
    ("Cloudflare", "platform", []),
    ("Kubernetes", "platform", ["K8s"]),
    ("Docker", "platform", []),
    ("PostgreSQL", "platform", ["Postgres", "psql"]),
    ("MySQL", "platform", []),
    ("MongoDB", "platform", ["Mongo"]),
    ("Redis", "platform", []),
    ("Elasticsearch", "platform", ["ES", "Elastic"]),
    ("Kafka", "platform", ["Apache Kafka"]),
    ("RabbitMQ", "platform", []),
    ("Snowflake", "platform", []),
    ("BigQuery", "platform", []),
    # ─── Tools ────────────────────────────────────────────────────
    ("Git", "tool", []),
    ("GitHub Actions", "tool", ["GH Actions"]),
    ("CI/CD", "tool", ["CICD", "Continuous Integration"]),
    ("Terraform", "tool", []),
    ("Webpack", "tool", []),
    ("Vite", "tool", []),
    ("Jest", "tool", []),
    ("Cypress", "tool", []),
    ("Playwright", "tool", []),
    ("Figma", "tool", []),
    ("Jira", "tool", []),
    # ─── Domain expertise ────────────────────────────────────────
    (
        "Payment Integration",
        "domain",
        ["Payments", "Payment Gateways", "Stripe", "Razorpay", "PayPal"],
    ),
    ("Real-time Systems", "domain", ["Realtime", "WebSockets"]),
    ("WebSocket", "domain", ["WebSockets", "WS"]),
    ("Machine Learning", "domain", ["ML"]),
    ("LLM Engineering", "domain", ["LLMs", "Generative AI", "GenAI", "Prompt Engineering"]),
    ("Computer Vision", "domain", ["CV"]),
    ("NLP", "domain", ["Natural Language Processing"]),
    ("Data Engineering", "domain", ["ETL", "Data Pipelines"]),
    ("DevOps", "domain", ["SRE", "Platform Engineering"]),
    ("Microservices", "domain", []),
    ("REST API", "domain", ["REST", "RESTful API"]),
    ("GraphQL", "domain", []),
    ("Authentication", "domain", ["OAuth", "JWT", "SSO"]),
    ("Healthcare", "domain", ["HealthTech", "HIPAA"]),
    ("Fintech", "domain", ["Banking", "Finance"]),
    ("E-commerce", "domain", ["Ecommerce"]),
    ("System Design", "domain", ["Architecture", "Scalability"]),
    ("Mobile Development", "domain", ["iOS", "Android"]),
    ("Frontend Development", "domain", ["UI Development"]),
    ("Backend Development", "domain", ["Server-side"]),
    ("Full-Stack Development", "domain", ["Full Stack", "Fullstack"]),
    ("Team Leadership", "domain", ["Tech Lead", "Engineering Management"]),
]
